name: RenderKeepAlive

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '*/10 13-22 * * 1-5'

  workflow_dispatch:

permissions:
  contents: write

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run script...
        run: |
          python3 main.py
